
DROP TABLE IF EXISTS MENUS RESTRICT;


DROP TABLE IF EXISTS ORDER_MENUS RESTRICT;


DROP TABLE IF EXISTS TORDERS RESTRICT;


CREATE TABLE MENUS (
	MNO    INTEGER     NOT NULL,
	MNAME  VARCHAR(50) NULL,
	MPRICE INTEGER     NULL,
	RDATE  DATE        NULL
);



ALTER TABLE MENUS
	ADD CONSTRAINT PK_MENUS
		PRIMARY KEY (
			MNO
		);

ALTER TABLE MENUS
	MODIFY COLUMN MNO INTEGER NOT NULL AUTO_INCREMENT;


CREATE TABLE ORDER_MENUS (
	MNO  INTEGER NOT NULL,
	ONO  INTEGER NOT NULL,
	OMNO INTEGER NOT NULL,
	NUM INTEGER NOT NULL DEFAULT 1
);


ALTER TABLE ORDER_MENUS
	ADD CONSTRAINT PK_ORDER_MENUS
	PRIMARY KEY (
			OMNO
		);

ALTER TABLE ORDER_MENUS
	MODIFY COLUMN OMNO INTEGER NOT NULL AUTO_INCREMENT;


CREATE TABLE TORDERS (
	ONO    INTEGER NOT NULL,
	TNO    INTEGER NULL,
	TPRICE INTEGER NULL,
	ODATE  DATE    NULL
);


ALTER TABLE TORDERS
	ADD CONSTRAINT PK_TORDERS
		PRIMARY KEY (
			ONO
		);

ALTER TABLE TORDERS
	MODIFY COLUMN ONO INTEGER NOT NULL AUTO_INCREMENT;


ALTER TABLE ORDER_MENUS
	ADD CONSTRAINT FK_MENUS_TO_ORDER_MENUS
		FOREIGN KEY (
			MNO
		)
		REFERENCES MENUS (
			MNO
		);


ALTER TABLE ORDER_MENUS
	ADD CONSTRAINT FK_TORDERS_TO_ORDER_MENUS
		FOREIGN KEY (
			ONO
		)
		REFERENCES TORDERS (
			ONO
		); 